### ISSUE TITLE
Unable to run qarv

### ISSUE THREAD

**Issue by FilipaRamos** [AD-Vega/qarv#14]
Hello! First of all, thanks for your work on this!

I was trying to run qarv over X11 forwarding, however, the window shows up entirely black and this message keeps repeating on the console:

```composeAndFlush: makeCurrent() failed```

Do you have any idea what could be happening here? I do not find anything useful on the internet. I am using Solus with all the qt5 packages updated and aravis 0.6.

Thanks!

**Comment by exzombie** [comment]
That the window would show up entirely black is quite weird. It is not be surprising for the video and histogram displays since they use OpenGL, but the rest of the window should be "normal". It is possible that Solus enables the OpenGL graphics engine for Qt, which most distros don't do. In any case, hardware acceleration is not available through X11 forwarding, and video is a lot of data to send through SSH. You can try running QArv as

    QT_GRAPHICSSYSTEM="native" LIBGL_ALWAYS_SOFTWARE=1 qarv

Using the native engine should give you a boost when running Qt apps through SSH. The `LIBGL_ALWAYS_SOFTWARE` variable only works with mesa OpenGL drivers (Intel or AMD), but not proprietary Nvidia or AMD drivers. I don't know how to force software rendering for those; it's possible that it's not even neccessary to enable explicitly, but if you still have problems, you can look into that. For what it's worth, I just tested qarv through X11 forwarding and it works out of the box for me with mesa drivers.

I'll close this issue since it's not something that can be fixed, but you are of course welcome to ask if you have further questions.

**Comment by FilipaRamos** [comment]
I have tested qarv without x11 and it works properly. So it really seems to be a problem with qt, libgl and x11 together. I have found bug reports of this but it seems not to be solved yet. Thanks a lot anyway!
