### ISSUE TITLE
error: ‘endl’ is not a member of ‘Qt’ and library dependencies

### ISSUE THREAD

**Issue by migraichen** [AD-Vega/qarv#22]
compiling fails with the error " ‘endl’ is not a member of ‘Qt’ "
i can get over this by replacing all Qt::endl with "\n".

on Ubuntu 20.04.1 I had to manually add libilmbase12_2.2.0-11ubuntu2_amd64.deb and libopenexr22_2.2.0-10ubuntu2_amd64.deb to run the program.
Also after install the library libqarv-3.so.3 needs to be moved to a library-folder before starting the program.

**Comment by exzombie** [comment]
Thanks for the report. I'll take a look soonish. I need to know a bit more, though: you say that you had to move the library. From where to where, exactly?

**Comment by migraichen** [comment]
hey, i've copied it from the build folder to /usr/local/lib/x86_64-linux-gnu
since this is where aravis moves its library too. 
But it probably depends on the distro. 
"sudo /sbin/ldconfig -v" should give you the paths and libs that get looked up by the system.

**Comment by exzombie** [comment]
Well, I've had mixed results.

I've used CMake-provided magic to get proper install paths. However, it will only work properly it you install to `/usr` by defining `-DCMAKE_INSTALL_PREFIX=/usr`. Installing to `/usr/local`, which is the default, will exhibit the same problem as before because CMake and Ubuntu [disagree on what is the proper path in this case](https://gitlab.kitware.com/cmake/cmake/-/issues/20565).

As for the `Qt::endl` issue, I'm not sure what I can do. The "bare" `endl` is deprecated since Qt 5.14 or 5.15 (not sure), and we're supposed to use fully-specified `Qt::endl`. But Ubuntu 20.04 comes with Qt 5.12, which doesn't have that. Using `"\n"` instead is not a good workaround because we'd need to add `Qt::flush` as well, and it has the same problem as `Qt::endl`.

@KlemenBlokar @alajovic @shrx Any ideas?

**Comment by migraichen** [comment]
Hey, I agree that "\n" is more a quick hack than a solution. For that I'm probably going to update my QT and leave this as a note for other Ubuntu users. 
The contradicting about using this on Ubuntu 20.04 is having to install libilmbase12 and libopenexr22 that come from Ubuntu 18.04 and got dropped in 20.04 but the QT version in Ubuntu 20.04 seems to be to old.

**Comment by exzombie** [comment]
Interesting, I set up a fresh Ubuntu 20.04 container in order to test this, and did not need to install neither libilmbase12 nor libopenexr22. I'm sure this must be specific to your system; if I had to guess, I'd say you have some remnants somewhere that were left after a distribution upgrade. Or perhaps something that you installed manually sometime in the past.

**Comment by exzombie** [comment]
Ah, to hell with it, let's just use the deprecated `endl`. I hate looking at warnings, but I guess working software has priority, right? ;)

**Comment by JanWielemaker** [comment]
Went for good old macros.  After all I'm a C programmer rather than a C++ one :smile: 

```
#include <QtGlobal>

#if QT_VERSION >= QT_VERSION_CHECK(5,14,0)
#define ENDL Qt::endl
#else
#define ENDL endl
#endif
```

**Comment by chryswoods** [comment]
Just found this issue (thanks!) and wanted to add that I solved this in a more C++ way ;-)

I also used this approach for `QString::SkipEmptyParts`

```
#include <QtGlobal>
#include <QString>

#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
namespace Qt
{
    static auto endl = ::endl;
    static auto SkipEmptyParts = QString::SkipEmptyParts;
}
#endif

**Comment by tycho-kirchner** [comment]
Thanks. A bit late to the party, but to also use the enum type `SplitBehavior`, one can:
~~~
#include <QtGlobal>
#include <QString>

#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
namespace Qt
{
    using SplitBehavior = QString::SplitBehavior;
    const SplitBehavior SkipEmptyParts = SplitBehavior::SkipEmptyParts;
    const auto endl = ::endl;
}
#endif
~~~
